import { Router } from "express";
import authRoutes from "./auth";
import userRoutes from "./users";
import agentRoutes from "./agents";
import productRoutes from "./products";
import salesRoutes from "./sales";
import payrollRoutes from "./payroll";
import serviceRoutes from "./service";
import webhookRoutes from "./webhooks";
import callAuditRoutes from "./call-audits";
import changeRequestRoutes from "./change-requests";
import callLogRoutes from "./call-logs";
import chargebackRoutes from "./chargebacks";
import csRepRoutes from "./cs-reps";
import pendingTermRoutes from "./pending-terms";
import alertRoutes from "./alerts";
import aiBudgetRoutes from "./ai-budget";
import adminRoutes from "./admin";
import archiveRoutes from "./archive";
import leadTimingRoutes from "./lead-timing";
import contactAttemptRoutes from "./contact-attempts";

const router = Router();

router.use(authRoutes);
router.use(userRoutes);
router.use(agentRoutes);
router.use(productRoutes);
router.use(salesRoutes);
router.use(payrollRoutes);
router.use(serviceRoutes);
router.use(webhookRoutes);
router.use(callAuditRoutes);
router.use(changeRequestRoutes);
router.use(callLogRoutes);
router.use(chargebackRoutes);
router.use(csRepRoutes);
router.use(pendingTermRoutes);
router.use(alertRoutes);
router.use(aiBudgetRoutes);
router.use(adminRoutes);
router.use(archiveRoutes);
router.use(leadTimingRoutes);
router.use(contactAttemptRoutes);

export default router;
